# Generated by Django 6.0.5 on 2026-05-25 18:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=200)),
                ('raca', models.CharField(max_length=50)),
                ('porte', models.CharField(choices=[('grande', 'Grande'), ('médio', 'Médio'), ('pequeno', 'Pequeno')], default='pequeno', max_length=10)),
                ('idade', models.IntegerField()),
                ('status_adocao', models.CharField(choices=[('disponível', 'Disponível'), ('adotado', 'Adotado')], default='disponível', max_length=30)),
                ('ong_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ong')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField()),
                ('veterinario', models.CharField(max_length=150)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.pet')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
