# Generated by Django 6.0.5 on 2026-05-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consulta',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ong',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pet',
            managers=[
            ],
        ),
    ]
